#!/usr/bin/perl

use strict;
use lib "/opt/vyatta/share/perl5/";
use XorpConfigParser;

my $orig_cfg = shift;
exit 1 if (!defined($orig_cfg));

my $xcp = new XorpConfigParser();
$xcp->parse($orig_cfg);
# comment out invalid config that was "valid" (but "wrong") in old version.
my $fw_node = $xcp->get_node(['firewall']);
my $fw_children = $fw_node->{'children'};
my @fw_names = $xcp->copy_multis($fw_children, 'name');
foreach my $fw_name (@fw_names) {
  my @rules = $xcp->copy_multis($fw_name->{'children'}, 'rule');
  foreach my $rule (@rules) {
    my $comment = undef;
    for (1 .. 1) {
      my $state = $xcp->find_child($rule->{'children'}, 'state');
      my $proto = $xcp->find_child($rule->{'children'}, 'protocol');
      if (defined($state)) {
        if (!defined($proto)) {
          $comment = '"state" can only be used with "protocol tcp"';
          last;
        } else {
          my $prot = $proto->{'value'};
          $prot =~ s/^"(.*)"$/$1/;
          if ($prot ne 'tcp') {
            $comment = '"state" can only be used with "protocol tcp"';
            last;
          }
        }
      }
    }
    if (defined($comment)) {
      $xcp->comment_out_child($fw_name->{'children'}, "rule $rule->{'name'}",
                              $comment);
    }
  }
}

my $tmpfile = "/tmp/vyatta_migrate_firewall.$$";
open(TMPFILE, ">$tmpfile") or exit 1;
select TMPFILE;

$xcp->output(0);

close TMPFILE;
my $ret = system("mv $tmpfile $orig_cfg");
exit 1 if ($ret >> 8);

exit 0;

