#! /usr/bin/perl

use strict;
use warnings;

use lib "/opt/vyatta/share/perl5/";
use XorpConfigParser;
use File::Copy;

my $orig_cfg = shift;
exit 1 unless $orig_cfg;

my $xcp = new XorpConfigParser();
$xcp->parse($orig_cfg);

my $interfaces = $xcp->get_node(['interfaces']);
exit 0 unless $interfaces; # tunnel interfaces not configured

my $intf_children = $interfaces->{'children'};
if (defined $intf_children){
  foreach my $intf (@{$intf_children}){
     if ( $intf->{'name'} =~ /tunnel tun[0-9]*/ ){
       for my $intf_child (@{$intf->{'children'}}){
         if ( ($intf_child->{'name'} =~ /tos/) or
              ($intf_child->{'name'} =~ /ttl/) or
              ($intf_child->{'name'} =~ /key/) ) {
            $xcp->create_node(['interfaces', $intf->{'name'}, 'parameters', 'ip', $intf_child->{'name'}]);
            $xcp->comment_out_node($intf_child);
         } elsif ($intf_child->{'name'} =~ /bridge-group/) {
            foreach my $bridge_option (@{$intf_child->{'children'}}){
              $xcp->create_node(['interfaces', $intf->{'name'}, 'parameters', 'ip', $intf_child->{'name'}, $bridge_option->{'name'}]);
            }
            $xcp->comment_out_node($intf_child);
         }
       }
     }
  }

## Move conntrack settings from "firewall" to "system conntrack"

my $fw = $xcp->get_node(['firewall']);
exit 0 unless $fw; # firewall is not configured

# Create "system conntrack" branch
$xcp->create_node(['system', 'conntrack']);

my $fw_children = $fw->{'children'};
  foreach my $child (@{$fw_children}) {
    my ($name, $value) = split(/ /, $child->{'name'});
    if ( $name =~ /conntrack-expect-table-size/ ) {
      $xcp->set_value(['system', 'conntrack', 'expect-table-size'], $value);
      $xcp->comment_out_node($child);
    }
    elsif( $name =~ /conntrack-hash-size/ ) {
      $xcp->set_value(['system', 'conntrack', 'hash-size'], $value);
      $xcp->comment_out_node($child);
    }
    elsif( $name =~ /conntrack-table-size/ ) {
      $xcp->set_value(['system', 'conntrack', 'table-size'], $value);
      $xcp->comment_out_node($child);
    }
    elsif( $name =~ /conntrack-tcp-loose/ ) {
      $xcp->set_value(['system', 'conntrack', 'tcp-loose'], $value);
      $xcp->comment_out_node($child);
    }
    elsif( $name =~ /conntrack-options/ ) {
      $xcp->create_node(['system', 'conntrack', 'modules']);
      $xcp->move_child($xcp->get_node(['firewall', 'conntrack-options']), $xcp->get_node(['system', 'conntrack', 'modules']), 'sip');
      $xcp->comment_out_node($child);
    }
  }

  my $tmpname = "/tmp/vyatta_migrate_tunnel_options.$$";
  open (my $tmp, '>', $tmpname)
    or die "Can't open: $tmpname: $!";

  select $tmp;
  $xcp->output(0);
  select STDOUT;
  close $tmp;

  move($tmpname, $orig_cfg)
    or die "Move $tmpname to $orig_cfg failed: $!";
}

exit 0;